#!/usr/bin/env python3
"""Regenerate the <Triggers> block of GammaX-Snapshot.xml.

Every scheduled occurrence gets its own CalendarTrigger instead of riding a
<Repetition> inside one. The reason is measured, not stylistic: Task
Scheduler's WakeToRun wakes the machine for a trigger's START BOUNDARY, and
never for a repetition inside a trigger's duration. On the snapshot branch,
2026-09-21 through 09-23, the three start boundaries fired unattended every
day and none of the other 47 occurrences ever did - 3 for 3 against 0 for 141.
Making each occurrence a start boundary puts every run on the one mechanism
that demonstrably wakes this machine.

This costs ~50 wake-ups a day of a few seconds each. market_sleep.bat still
holds the machine awake across the session, so in practice it wakes once at
09:15 and stays up; the triggers are what carry the day if that fails. Either
mechanism alone is enough, which is the point of having both.

Edit SCHEDULE below and re-run:

    python tools/make_schedule.py

It rewrites the file in place and leaves settings, principal and actions
untouched.
"""
import pathlib
import re
from datetime import datetime, timedelta

XML = pathlib.Path(__file__).with_name("GammaX-Snapshot.xml")

WEEKDAYS = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

# (label, first, last, every N minutes, days) - `last` is inclusive.
SCHEDULE = [
    ("Session: every 15 minutes, 09:15 through 14:45, weekdays",
     "09:15", "14:45", 15, WEEKDAYS),
    ("Close window: every 5 minutes, 15:00 through 16:45, weekdays",
     "15:00", "16:45", 5, WEEKDAYS),
    ("Settlement follow-up, weekdays",
     "18:20", "18:20", 0, WEEKDAYS),
    ("Off-hours, every day",
     "20:00", "20:00", 0, None),
    ("Off-hours, every day", "00:00", "00:00", 0, None),
    ("Off-hours, every day", "04:00", "04:00", 0, None),
    ("Off-hours, every day", "08:00", "08:00", 0, None),
]


def times(first, last, step):
    t = datetime.strptime(first, "%H:%M")
    end = datetime.strptime(last, "%H:%M")
    if step <= 0:
        return [t]
    out = []
    while t <= end:
        out.append(t)
        t += timedelta(minutes=step)
    return out


def trigger(when, days):
    """One CalendarTrigger. Child order follows the 18:00 trigger that the
    hand-written file already used successfully: StartBoundary, Enabled,
    then the schedule element."""
    body = [
        "    <CalendarTrigger>",
        f"      <StartBoundary>2026-01-01T{when:%H:%M}:00</StartBoundary>",
        "      <Enabled>true</Enabled>",
    ]
    if days:
        body.append("      <ScheduleByWeek>")
        body.append("        <DaysOfWeek>")
        body += [f"          <{d} />" for d in days]
        body.append("        </DaysOfWeek>")
        body.append("        <WeeksInterval>1</WeeksInterval>")
        body.append("      </ScheduleByWeek>")
    else:
        body.append("      <ScheduleByDay>")
        body.append("        <DaysInterval>1</DaysInterval>")
        body.append("      </ScheduleByDay>")
    body.append("    </CalendarTrigger>")
    return body


def build():
    lines = ["  <Triggers>",
             "    <!-- GENERATED by tools/make_schedule.py - do not hand-edit.",
             "         One trigger per occurrence, deliberately: WakeToRun wakes the",
             "         machine for a START BOUNDARY and never for a repetition inside",
             "         a trigger's duration, so a <Repetition> here loses every run",
             "         behind the first one on a machine that sleeps. Measured 09-21",
             "         to 09-23: 3 of 3 start boundaries fired unattended, 0 of 141",
             "         repetitions did. -->"]
    total = 0
    for label, first, last, step, days in SCHEDULE:
        when = times(first, last, step)
        total += len(when)
        lines.append(f"    <!-- {label}. {len(when)} run"
                     f"{'s' if len(when) != 1 else ''}. -->")
        for t in when:
            lines += trigger(t, days)
    lines.append("  </Triggers>")
    return "\n".join(lines), total


def main():
    src = XML.read_text()
    block, total = build()
    out, n = re.subn(r"  <Triggers>.*?</Triggers>", lambda _: block, src,
                     count=1, flags=re.S)
    if n != 1:
        raise SystemExit("could not find a single <Triggers> block to replace")
    XML.write_text(out)
    print(f"{XML.name}: {total} triggers written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
