#!/usr/bin/env python3
"""Regenerate the scheduled-task XML from the SCHEDULE tables below.

    python tools/make_schedule.py

Every scheduled occurrence gets its own CalendarTrigger instead of riding a
<Repetition> inside one. The reason is measured, not stylistic: Task
Scheduler's WakeToRun wakes the machine for a trigger's START BOUNDARY, and
never for a repetition inside a trigger's duration. On the snapshot branch,
2026-09-21 through 09-23, the three start boundaries fired unattended every
day and none of the other 47 occurrences ever did - 3 for 3 against 0 for 141.
Making each occurrence a start boundary puts every run on the one mechanism
that demonstrably wakes this machine.

This costs ~50 wake-ups a day of a few seconds each. market_sleep.bat still
holds the machine awake across the session, so in practice it wakes once at
09:15 and stays up; the triggers are what carry the day if that fails. Either
mechanism alone is enough, which is the point of having both.

WHY THERE ARE TWO TASKS
-----------------------
Task Scheduler accepts at most MAX_TRIGGERS triggers in one task and rejects
the whole document past that, with a message that never names the limit:

    The task XML contains too many nodes of the same type.
    (680,7):CalendarTrigger:

Measured on Windows 11 26200 by registering the real file truncated to each
length: 46, 47 and 48 registered, 49 and 50 were rejected. The full schedule is
50 occurrences, so it is split across two tasks that between them cover the
day. Both run the same publisher; nothing else differs. The windows do not
overlap, and the narrowest gap between one task's last run and the other's
first is 15 minutes against runs that take about ten seconds.

The check in build_all() is the point of this note: an edit that pushes a task
back over the limit now fails here, loudly, instead of writing a file that
silently will not register - which is what happened, and cost two days of
snapshots that looked scheduled and were not.
"""
import pathlib
import re
from datetime import datetime, timedelta

HERE = pathlib.Path(__file__).parent
TEMPLATE = HERE / "GammaX-Snapshot.xml"      # also one of the outputs

# Hard ceiling enforced by Task Scheduler itself; see the module docstring.
MAX_TRIGGERS = 48

WEEKDAYS = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

# (label, first, last, every N minutes, days) - `last` is inclusive,
# step 0 means a single occurrence, days None means every day.
SESSION = [
    ("Session: every 15 minutes, 09:15 through 14:45, weekdays",
     "09:15", "14:45", 15, WEEKDAYS),
    ("Settlement follow-up, weekdays", "18:20", "18:20", 0, WEEKDAYS),
    ("Off-hours, every day", "20:00", "20:00", 0, None),
    ("Off-hours, every day", "00:00", "00:00", 0, None),
    ("Off-hours, every day", "04:00", "04:00", 0, None),
    ("Off-hours, every day", "08:00", "08:00", 0, None),
]

CLOSE = [
    ("Close window: every 5 minutes, 15:00 through 16:45, weekdays",
     "15:00", "16:45", 5, WEEKDAYS),
]

# (output file, task name/URI, one-line role, schedule)
TASKS = [
    (TEMPLATE, "Gamma_X Snapshot",
     "Weekdays every 15 minutes from 09:15 to 14:45, once at 18:20, and daily "
     "at 00:00, 04:00, 08:00 and 20:00.", SESSION),
    (HERE / "GammaX-Snapshot-Close.xml", "Gamma_X Snapshot Close",
     "Weekdays every 5 minutes from 15:00 to 16:45, the cash close and the "
     "hour after it.", CLOSE),
]

DESCRIPTION = (
    "Generates the GEX dashboard and publishes it to the snapshot branch that "
    "GitHub Pages serves. {role} Runs only push when the figures actually "
    "change (--skip-unchanged). All times are the machine's local clock, so "
    "set it to Eastern. Each occurrence is its own trigger, generated by "
    "tools/make_schedule.py - WakeToRun wakes the PC for a trigger's START "
    "BOUNDARY and never for a repetition inside a trigger's duration, so the "
    "repetitions this used to use were lost on a sleeping machine: 3 of 3 "
    "start boundaries fired unattended over 09-21 to 09-23, and 0 of 141 "
    "repetitions did. The day is split across two tasks because Task "
    "Scheduler rejects a document with more than 48 triggers and the full "
    "schedule is 50. publish_snapshot.bat also holds the machine awake across "
    "the session by setting both sleep timers, the attended idle one and the "
    "unattended one whose 120s default was returning the PC to sleep after "
    "each run. Either mechanism alone is enough; both are in place because "
    "this failed twice."
)


def times(first, last, step):
    t = datetime.strptime(first, "%H:%M")
    end = datetime.strptime(last, "%H:%M")
    if step <= 0:
        return [t]
    out = []
    while t <= end:
        out.append(t)
        t += timedelta(minutes=step)
    return out


def trigger(when, days):
    """One CalendarTrigger. Child order follows the 18:00 trigger that the
    hand-written file already used successfully: StartBoundary, Enabled,
    then the schedule element."""
    body = [
        "    <CalendarTrigger>",
        f"      <StartBoundary>2026-01-01T{when:%H:%M}:00</StartBoundary>",
        "      <Enabled>true</Enabled>",
    ]
    if days:
        body.append("      <ScheduleByWeek>")
        body.append("        <DaysOfWeek>")
        body += [f"          <{d} />" for d in days]
        body.append("        </DaysOfWeek>")
        body.append("        <WeeksInterval>1</WeeksInterval>")
        body.append("      </ScheduleByWeek>")
    else:
        body.append("      <ScheduleByDay>")
        body.append("        <DaysInterval>1</DaysInterval>")
        body.append("      </ScheduleByDay>")
    body.append("    </CalendarTrigger>")
    return body


def build(schedule):
    lines = ["  <Triggers>",
             "    <!-- GENERATED by tools/make_schedule.py - do not hand-edit.",
             "         One trigger per occurrence, deliberately: WakeToRun wakes the",
             "         machine for a START BOUNDARY and never for a repetition inside",
             "         a trigger's duration, so a <Repetition> here loses every run",
             "         behind the first one on a machine that sleeps. Measured 09-21",
             "         to 09-23: 3 of 3 start boundaries fired unattended, 0 of 141",
             "         repetitions did.",
             "",
             "         At most 48 per task - Task Scheduler rejects the whole document",
             "         past that, which is why the day's 50 runs live in two tasks. -->"]
    total = 0
    for label, first, last, step, days in schedule:
        when = times(first, last, step)
        total += len(when)
        lines.append(f"    <!-- {label}. {len(when)} run"
                     f"{'s' if len(when) != 1 else ''}. -->")
        for t in when:
            lines += trigger(t, days)
    lines.append("  </Triggers>")
    return "\n".join(lines), total


def build_all():
    """Write every task file. Returns (filename, task name, trigger count)."""
    template = TEMPLATE.read_text()
    written = []
    for path, name, role, schedule in TASKS:
        block, total = build(schedule)
        if total > MAX_TRIGGERS:
            raise SystemExit(
                f"{path.name}: {total} triggers, but Task Scheduler accepts at "
                f"most {MAX_TRIGGERS} and rejects the whole document past that "
                f'with "too many nodes of the same type". Move some '
                f"occurrences into another entry in TASKS.")

        out, n = re.subn(r"  <Triggers>.*?</Triggers>", lambda _: block,
                         template, count=1, flags=re.S)
        if n != 1:
            raise SystemExit("could not find a single <Triggers> block")
        out, n = re.subn(r"<URI>[^<]*</URI>",
                         lambda _: f"<URI>\\{name}</URI>", out, count=1)
        if n != 1:
            raise SystemExit("could not find the <URI> element")
        out, n = re.subn(r"(?s)<Description>.*?</Description>",
                         lambda _: "<Description>"
                                   + DESCRIPTION.format(role=role)
                                   + "</Description>",
                         out, count=1)
        if n != 1:
            raise SystemExit("could not find the <Description> element")

        path.write_text(out)
        written.append((path.name, name, total))
    return written


def main():
    written = build_all()
    for filename, name, total in written:
        print(f"{filename:<28} {name:<24} {total:>2} triggers "
              f"({MAX_TRIGGERS - total} under the limit)")
    print(f"\n{sum(t for _, _, t in written)} runs per weekday across "
          f"{len(written)} tasks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
